---
# =====================================
# ROL: DOCKER
# Descripción: Instala y configura Docker en el sistema
# =====================================

# Verificar instalación actual de Docker
- name: Verificar si Docker está instalado
  stat:
    path: /usr/bin/docker
  register: docker_check

# Instalar dependencias necesarias para Docker
- name: Instalar dependencias del sistema para Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: true
  when: not docker_check.stat.exists

# Agregar clave GPG oficial de Docker
# NOTA: Si utilizas otra distribución, cambia la URL del repositorio
- name: Agregar clave GPG oficial de Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: not docker_check.stat.exists

# Agregar repositorio de Docker
# NOTA: Si utilizas otra distribución, cambia la URL del repositorio
- name: Agregar repositorio de Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true
  when: not docker_check.stat.exists

# Instalar Docker Engine
- name: Instalar Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  become: true
  when: not docker_check.stat.exists

# Verificar Docker Compose
- name: Verificar si Docker Compose está instalado
  stat:
    path: /usr/libexec/docker/cli-plugins/docker-compose
  register: compose_check

# Instalar Docker Compose plugin v2
- name: Instalar Docker Compose plugin (v2)
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: true
  become: true
  #when: not compose_check.stat.exists
  when: false

# Agregar usuario al grupo docker para ejecutar comandos sin sudo
- name: Agregar usuario actual al grupo docker
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
  when: not docker_check.stat.exists

# Reiniciar el servicio de Docker para aplicar cambios  
- name: Reiniciar el servicio de Docker
  service:
    name: docker
    state: restarted
  become: true
  when: not docker_check.stat.exists
